services:
  backend:
    restart: always
    build:
      context: oregon-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
      MSSQL_SA_PASSWORD: "@Cendy123"
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db-data/data:/var/opt/mssql/data
      - ./db-data/log:/var/opt/mssql/log
      - ./db-data/secrets:/var/opt/mssql/secrets
    ports:
      - "1433:1433"
